#*********************** THE APP *****************************

# We are storing all the configuration values here which we are passing to our test scripts & basetest


###MOBILE CONFIG###

#Device Details 
DEVICE_NAME = Gangadhar

#Apk Details
APK_NAME =TheApp.apk
APK_PATH=\\src\\test\\resources\\testapk\\
APP_PACKAGE_NAME=com.appiumpro.the_app


#Appium Server Configs Paths
IP_ADDRESS=127.0.0.1
port=4723
NODE_PATH=C:/Program Files/nodejs/node.exe
APPIUM_JSPATH=/AppData/Roaming/npm/node_modules/appium/build/lib/main.js
SERVER_URL=http://127.0.0.1:4723

MOBILE_TESTURL=

###WEB CONFIG###

#Web User Credentils
TEST_URL=

#DB Credentials
DATABASE_URL=
DATABASE_USR=
DATABASE_PASSWORD=








