#*********************** THE APP *****************************

# We are storing all the configuration values here which we are passing to our test scripts & basetest


###MOBILE CONFIG###

#Device Details 
DeviceName = Gangadhar

#Apk Details
ApkName =TheApp.apk
apkPath=\\src\\test\\resources\\testapk\\
appPackageName=com.appiumpro.the_app


#Appium Server Configs Paths
ipAddress=127.0.0.1
port=4723
nodePath=C:/Program Files/nodejs/node.exe
appiumJSpath=/AppData/Roaming/npm/node_modules/appium/build/lib/main.js
serverUrl=http://127.0.0.1:4723



###WEB CONFIG###

# User Credentils
TestURL=https://nimbleglowqa.nimblelos.com:8093/








